### ISSUE TITLE
ModuleNotFoundError: No module named 'pya2l.py3'

### ISSUE THREAD

**Issue by kmasif** [christoph2/pyA2L#5]
Hi @christoph2, 

Since there is no information related to installation, after cloning the repo I used the usual command to setup python package from souce:
`python setup.py install`

Looks like all went well. When I tried to test the package with the built-in test you have @ [pyA2L/pya2l/tests/testA2LAcceptance.py](url)

It gives me a _ModuleNotFoundError: No module named 'pya2l.py3'_

Below is the log, 
`$ py test.py
Traceback (most recent call last):
  File "test.py", line 617, in <module>
    parser.parseFromString(TEST_A2L)
  File "D:\Python\36\lib\site-packages\pya2l-0.1.0-py3.6.egg\pya2l\a2lparser.py", line 265, in parseFromString
  File "D:\Python\36\lib\site-packages\pya2l-0.1.0-py3.6.egg\pya2l\a2lparser.py", line 268, in parse
  File "D:\Python\36\lib\site-packages\pya2l-0.1.0-py3.6.egg\pya2l\aml.py", line 63, in __init__
  File "D:\Python\36\lib\site-packages\pya2l-0.1.0-py3.6.egg\pya2l\aml.py", line 69, in _load
  File "D:\Python\36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pya2l.py3'
`

Am I doing something wrong with the setup? Your response will be highly appreciated.

**Comment by andip** [comment]
Got the same error. I'm using Python 3.6.1. Did you already find a solution for this issue?

**Comment by hongjiaoptim** [comment]
HI,my dear friend! I got the solution for you! cos i come with the same problem when i want to you the module.

when you install the package, check the setup.py file, make sure the packages = ['pya2l','pya2l.py2'].
in which the '2' can be '3', if you use python3.x   .  Try to install it again, and run you script, Hope you Engoy my solution. Any Question or thanks ^_^ can come to my email: hongjia1234@sina.com, my name is Hong Jia, from China.
